version: '3.9'
services:
  emonc:
    build: .
    container_name: emonc_c
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
    environment:
      - DB_URL=postgresql://dev:Mugumbaabu91@flask_db:5432/emonc
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=Mugumbaabu91
      - POSTGRES_USER=dev
      - POSTGRES_DB=emonc